language: ruby
rvm:
  - 1.9.3
script: 'nanoc compile'
notifications:
  irc:
    channels:
      - "irc.freenode.org#dtf-gems"
  email:
    recipients:
      - me@deryldoucette.com
    on_failure: all
